import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";

test("pending manual edits survive unrelated automatic revalidation", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto("./");
  await page.locator("#xml-upload").setInputFiles({ name: "demo.xml", mimeType: "application/xml", buffer: await readFile("public/samples/stix-validation-demo.stix") });
  await page.getByRole("button", { name: "Validate & Fix" }).last().click();
  await page.getByRole("button", { name: "Automatic fixes", exact: true }).click();
  await page.getByRole("button", { name: "Manual fixes", exact: true }).click();
  const relationship = page.getByRole("combobox", { name: "Relationship for Apple Crisp", exact: true });
  await relationship.selectOption("PARENT");
  await page.getByRole("button", { name: "Return to automatic fixes", exact: true }).last().click();
  await page.getByRole("button", { name: "Select fix for File metadata: MetadataContactPhone", exact: true }).click();
  await page.getByRole("button", { name: /Apply selected/ }).click();
  await page.getByRole("button", { name: "Manual fixes", exact: true }).click();
  await expect(relationship).toHaveValue("PARENT");
  await expect(page.getByText(/outdated because/)).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Apply selected (1)", exact: true })).toBeEnabled();
  await page.screenshot({ path: testInfo.outputPath("preserved-pending-edit.png") });
  await page.getByRole("button", { name: "Apply selected (1)", exact: true }).click();
  await expect(page.getByText(/outdated because/)).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Apply selected (0)", exact: true })).toBeDisabled();
});

test("page-wide intake and on-demand student context keep correction rows compact", async ({ page }, testInfo) => {
  await page.goto("./");
  const buffer = await readFile("public/samples/stix-validation-demo.stix");
  const transfer = await page.evaluateHandle((base64) => {
    const data = new DataTransfer();
    data.items.add(new File([Uint8Array.from(atob(base64), (char) => char.charCodeAt(0))], "demo.xml", { type: "application/xml" }));
    return data;
  }, buffer.toString("base64"));
  await page.locator("body").dispatchEvent("dragenter", { dataTransfer: transfer });
  await expect(page.getByText("Drop your XML or XLSM file anywhere")).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("page-drop.png") });
  await page.locator("body").dispatchEvent("drop", { dataTransfer: transfer });
  await transfer.dispose();
  await expect(page.getByText("demo.xml", { exact: true })).toBeVisible();
  await expect(page.locator(".page-file-drop")).toHaveCount(0);
  await page.getByRole("button", { name: "Validate & Fix" }).last().click();
  await page.getByRole("button", { name: "Automatic fixes", exact: true }).click();
  await expect(page.getByText("Unencrypted STIX · applied changes only")).toHaveCount(0);
  await page.getByRole("button", { name: /View student / }).first().click();
  const entry = page.getByRole("dialog", { name: "Complete student entry" });
  await expect(entry.locator("header")).toContainText("Student 1.2");
  await expect(entry.locator("header")).not.toContainText("Broccoli Sprout");
  await expect(entry.locator("dd").filter({ hasText: /^\s*Broccoli\s*$/ })).toBeVisible();
  await expect(entry.getByRole("heading", { name: "Address", exact: true })).toBeVisible();
  await expect(entry.getByRole("heading", { name: "Guardian 2", exact: true })).toBeVisible();
  await expect(entry.locator("input")).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath("student-entry.png") });
  await entry.getByRole("button", { name: "Close", exact: true }).click();
  await page.getByRole("button", { name: "Manual fixes", exact: true }).click();
  const field = page.locator(".field-location").filter({ hasText: /^Guardian2Relationship$/ }).first();
  await expect(field).toHaveAttribute("title", "SchoolUpload/School/Students/Student/Guardian[2]/Relationship");
  const duplicate = page.locator("tr").filter({ hasText: 'OEN "222333444" is duplicated' });
  await expect(duplicate.locator("td").nth(1)).toContainText("Student");
  await expect(duplicate.locator("td").nth(1)).not.toContainText("duplicated");
  await expect(duplicate.locator("td").nth(3)).toContainText('OEN "222333444" is duplicated');
  await expect(duplicate).toContainText("Resolve in the source file");
  await expect(duplicate.locator("input")).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath("compact-manual.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: /View student / }).first().click();
  await page.screenshot({ path: testInfo.outputPath("student-entry-mobile.png") });
  await page.keyboard.press("Escape");
  await expect(entry).toHaveCount(0);
});

test("page-wide drops reject multiple files and do not choose a comparison target", async ({ page }) => {
  await page.goto("./");
  const transfer = await page.evaluateHandle(() => {
    const data = new DataTransfer();
    for (const name of ["one.xml", "two.xml"]) data.items.add(new File(["<SchoolUpload/>"], name, { type: "application/xml" }));
    return data;
  });
  await page.locator("body").dispatchEvent("drop", { dataTransfer: transfer });
  await expect(page.getByText("Drop one XML or XLSM file at a time.")).toBeVisible();
  await page.getByRole("button", { name: "Compare Files", exact: true }).first().click();
  await page.locator("body").dispatchEvent("drop", { dataTransfer: transfer });
  await expect(page.getByText("one.xml", { exact: true })).toHaveCount(0);
  await expect(page.getByText("two.xml", { exact: true })).toHaveCount(0);
  await transfer.dispose();
});

test("manual address edits share the review table, survive staging, and undo after apply", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto("./");
  await page.locator("#xml-upload").setInputFiles({ name: "demo.xml", mimeType: "application/xml", buffer: await readFile("public/samples/stix-validation-demo.stix") });
  await page.getByRole("button", { name: "Validate & Fix" }).last().click();
  await expect(page.getByRole("heading", { name: "Quality assessment", exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("quality.png") });
  await page.getByRole("button", { name: "Automatic fixes", exact: true }).click();
  const select = page.getByRole("button", { name: /Select fix for/ }).first();
  await select.click();
  await expect(select).toHaveAttribute("aria-pressed", "true");
  await page.screenshot({ path: testInfo.outputPath("automatic.png") });
  await select.click();
  await page.getByRole("button", { name: "Manual fixes", exact: true }).click();
  await expect(page.getByRole("button", { name: "Return to automatic fixes", exact: true }).last()).toBeVisible();
  await expect(page.getByRole("button", { name: "Use suggested", exact: true })).toHaveCount(0);
  const addressRow = page.locator("tr").filter({ has: page.getByRole("button", { name: "Edit address", exact: true }) }).first();
  await addressRow.getByRole("button", { name: "Edit address", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Edit address", exact: true });
  await expect(dialog).not.toContainText(/school\d+:student\d+/);
  const streetNumber = dialog.getByRole("textbox", { name: /^Street number/i });
  await streetNumber.fill("123");
  await expect(streetNumber).toHaveValue("123");
  await page.screenshot({ path: testInfo.outputPath("address.png") });
  await dialog.getByRole("button", { name: "Back to fixes", exact: true }).click();
  await page.getByRole("button", { name: /Filter severity:/ }).click();
  await expect(page.getByRole("radio", { name: "All severities", exact: true })).toBeChecked();
  await page.screenshot({ path: testInfo.outputPath("severity-filter.png") });
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: /Filter severity:/ })).toHaveAttribute("aria-expanded", "false");
  await page.getByRole("button", { name: /Filter severity:/ }).click();
  await page.getByRole("radio", { name: "Errors only", exact: true }).check();
  await expect(page.getByRole("button", { name: "Filter severity: Errors only", exact: true })).toBeFocused();
  await expect(page.getByRole("button", { name: /Filter severity:/ })).toHaveAttribute("data-active", "true");
  await expect(page.getByText(/outdated because/)).toHaveCount(0);
  await page.getByRole("button", { name: /Filter severity:/ }).click();
  await page.getByRole("radio", { name: "All severities", exact: true }).check();
  await addressRow.getByRole("button", { name: "Edit address", exact: true }).click();
  await expect(streetNumber).toHaveValue("123");
  await dialog.getByRole("button", { name: "Back to fixes", exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath("manual.png") });

  // A progress file includes committed values, never pending field edits.
  const pendingDownload = page.waitForEvent("download");
  await page.getByRole("button", { name: "Save in-progress file", exact: true }).click();
  const progress = await pendingDownload;
  const progressPath = await progress.path();
  expect(progressPath).toBeTruthy();
  const before = await readFile(progressPath!, "utf8");
  expect(before).toContain("<ns1:StreetNumber>1234567</ns1:StreetNumber>");
  await page.getByRole("button", { name: /Apply selected/ }).click();
  await expect(page.getByRole("button", { name: /Undo last action/ })).toBeVisible();
  const log = page.getByRole("complementary", { name: "History" });
  await expect(log.getByRole("button", { name: /History/ })).toHaveAttribute("aria-expanded", "true");
  const mainBounds = await page.locator("main").boundingBox();
  const logBounds = await log.boundingBox();
  expect(logBounds!.x).toBeGreaterThanOrEqual(mainBounds!.x + mainBounds!.width);
  await page.screenshot({ path: testInfo.outputPath("action-log-desktop.png") });
  await page.getByRole("button", { name: "View summary", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Summary and Output", exact: true })).toBeVisible();
  const afterPending = page.waitForEvent("download");
  await page.getByRole("button", { name: "Save in-progress file", exact: true }).click();
  const after = await readFile((await (await afterPending).path())!, "utf8");
  expect(after).toContain("<ns1:StreetNumber>123</ns1:StreetNumber>");
  expect(after).not.toContain("<ns1:StreetNumber>1234567</ns1:StreetNumber>");
  await page.screenshot({ path: testInfo.outputPath("summary.png") });
  await page.getByRole("button", { name: /Undo last action/ }).click();
  const undoPending = page.waitForEvent("download");
  await page.getByRole("button", { name: "Save in-progress file", exact: true }).click();
  expect(await readFile((await (await undoPending).path())!, "utf8")).toBe(before);

  await page.setViewportSize({ width: 390, height: 844 });
  await expect(log.getByRole("button", { name: /History/ })).toHaveAttribute("aria-expanded", "false");
  await page.getByRole("button", { name: "Return to manual fixes", exact: true }).last().click();
  const nextButton = page.getByRole("button", { name: "View summary", exact: true });
  const bounds = await nextButton.boundingBox();
  expect(bounds).not.toBeNull();
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390);
  await page.screenshot({ path: testInfo.outputPath("manual-mobile.png") });
  await page.getByRole("button", { name: "Edit address", exact: true }).first().click();
  await expect(dialog).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("address-mobile.png") });
});
